server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/api/auth/oauth2/jwks
